<?php

declare(strict_types=1);

namespace App\Telegram\Notifications;

class AdminNotification extends AbstractNotification
{
    public function sendMessage(string $message, ?int $chatId = null): void
    {
        $adminGroup = config('telegram.admin_group');
        parent::sendMessage($message, $adminGroup); // TODO: Change the autogenerated stub
    }
}
